stages:
  # - kind
  # - minikube
  # - integration

sudo: required

jobs:
  include:
    # - stage: kind
    #   sudo: required
    #   language: go
    #   go: 1.16.x
    #   services:
    #     - docker
    #   before_script:
    #     # - ./scripts/setup_kind.sh
    #     - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.0.1/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
    #     - kind create cluster --image "kindest/node:v1.21.1"
    #   script:
    #     - ./scripts/setup_ketch.sh $TRAVIS_COMMIT
    #     - ./cli_tests/help.sh

    - stage: minikube
      sudo: required
      language: go
      go: 1.16.x
      services:
        - docker
      provider: script
      script:
        - bash scripts/install_kubectl.sh
        - bash scripts/install_minikube.sh
        - bash scripts/install_bats.sh
        - bash scripts/install_ketch.sh
        - bats cli_tests/app.sh

    # - stage: k3d
    #   sudo: required
    #   language: go
    #   go: 1.16.x
    #   services:
    #     - docker
    #   provider: script
    #   script:
    #     - bash scripts/install_kubectl.sh
    #     - bash scripts/install_k3d.sh
    #     - bash scripts/install_bats.sh
    #     - bash scripts/install_ketch.sh
