jobs:
  include:
    # - stage: install/lint
    #   language: go
    #   before_script:
    #     - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
    #   go: "1.16"
    #   script:
    #     - ./install_script.sh $TRAVIS_COMMIT
    #     - golangci-lint run --timeout 3m
    - stage: test
      sudo: required
      name: "Running integration tests"
      language: go
      go: 1.17.x
      services:
        - docker
      provider: script
      script:
        - bash install_kubectl.sh
        - bash install_minikube.sh
        # - bash install_bats.sh
        - bash install_ketch.sh