stages:
  - test

sudo: required

jobs:
  include:
    - stage: test
      sudo: required
      language: go
      go: 1.16.x
      dist: xenial
      install: ./scripts/install_script.sh $TRAVIS_COMMIT
